### PR TITLE
Build fix for 4.20-rc

### PR DESCRIPTION
**Pull request by wens**
Build fix for 4.20-rc, where a few APIs disappeared.

The other patch makes the GPU task aborts play nicer with the kernel.

### CODE REVIEW

**Comment by superna9999** [comment]
Thanks @wens !

Are `ktime_to_ns(ktime_get_boottime())` and `WARN_ON()` ok on older kernels ?

**Comment by wens** [comment]
`WARN_ON` is definitely OK.
I should add a guard for `ktime_to_ns(ktime_get_boottime())`.

**Comment by wens** [comment]
Branch is now updated. New API usage has guard macros, and some even have comments.

**Comment by superna9999** [comment]
Thanks, I also backported them to the DX910-SW-99002-r6p1-01rel0_meson_gx branch

**Pull request merged**
